In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv('Dataset-healthexp.csv')
df.head(10)

   Unnamed: 0  Year        Country  Spending_USD  Life_Expectancy
0           0  1970        Germany       252.311             70.6
1           1  1970         France       192.143             72.2
2           2  1970  Great Britain       123.993             71.9
3           3  1970          Japan       150.437             72.0
4           4  1970            USA       326.961             70.9
5           5  1971         Canada       313.391             72.8
6           6  1971        Germany       298.251             70.8
7           7  1971  Great Britain       134.172             71.9
8           8  1971          Japan       163.854             72.9
9           9  1971            USA       357.988             71.2

In [6]:
df.shape

(274, 5)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       274 non-null    int64
 1   Year             274 non-null    int64
 2   Country          274 non-null    object
 3   Spending_USD     274 non-null    float64
 4   Life_Expectancy  274 non-null    float64
dtypes: float64(2), int64(2), object(1)
memory usage: 10.8+ KB

In [7]:
df.columns

Index(['Unnamed: 0', 'Year', 'Country', 'Spending_USD', 'Life_Expectancy'], dtype='object')

In [12]:
df.isnull().sum()

Unnamed: 0         0
Year               0
Country            0
Spending_USD       0
Life_Expectancy    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

#### Déterminez quelles sont les variables Discrètes et Continues du dataset

In [26]:
df.head(10)

   Unnamed: 0  Year        Country  Spending_USD  Life_Expectancy
0           0  1970        Germany       252.311             70.6
1           1  1970         France       192.143             72.2
2           2  1970  Great Britain       123.993             71.9
3           3  1970          Japan       150.437             72.0
4           4  1970            USA       326.961             70.9
5           5  1971         Canada       313.391             72.8
6           6  1971        Germany       298.251             70.8
7           7  1971  Great Britain       134.172             71.9
8           8  1971          Japan       163.854             72.9
9           9  1971            USA       357.988             71.2

In [14]:
df.describe()

       Unnamed: 0         Year  Spending_USD  Life_Expectancy
count  274.000000   274.000000    274.000000       274.000000
mean   136.500000  1996.992701   2789.338905        77.909489
std     79.241193    14.180933   2194.939785         3.276263
min      0.000000  1970.000000    123.993000        70.600000
25%     68.250000  1985.250000   1038.357000        75.525000
50%    136.500000  1998.000000   2295.578000        78.100000
75%    204.750000  2009.000000   4055.610000        80.575000
max    273.000000  2020.000000  11859.179000        84.700000

In [20]:
df.dtypes

Unnamed: 0           int64
Year                 int64
Country             object
Spending_USD       float64
Life_Expectancy    float64
dtype: object

'Year' = Quatigorical data
'Country' = Quatigorical data
'Spending_USD' = Quantitative data --> variable Continue
'Life_Expectancy' = Quantitative data --> variable Continue

#### Analysez la variable "Country"